# Generated by Django 5.0.1 on 2024-04-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arama',
            name='release_status',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
