# Generated by Django 5.0.1 on 2024-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_arama_release_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arama',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='arama',
            name='enddate',
            field=models.DateField(null=True),
        ),
    ]
