# Generated by Django 5.0.1 on 2024-03-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_arama_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='arama',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
