# Generated by Django 5.0.1 on 2024-03-15 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_arama_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='arama',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
